### ISSUE TITLE
Getting java.io.IOException: Compressed with incompatible lzo version: 0x2090 (expected 0x2050)

### ISSUE THREAD

**Issue by ronakvorabr** [shevek/lzo-java#7]

**Comment by ronakvorabr** [comment]
UPDATE: 

I have updated the source code in lzoconf.h such that #define LZO_VERSION 0x2050 is now #define LZO_VERSION 0x2090. The file still decompresses correctly. 

I've attached a sample of the lzo file that didn't work with the current state of the code.

**Comment by victoryxs** [comment]
```java
public class testUnlzo {

  public static void main(String[] args) throws Exception{
    InputStream in = new FileInputStream(new File("C:\\Users\\victoryxs\\Desktop\\10.180.244.104_36310_20160218090000_S1_MME.csv.lzo"));
    LzoAlgorithm algorithm = LzoAlgorithm.LZO1X;
    LzoDecompressor decompressor = LzoLibrary.getInstance().newDecompressor(algorithm, null);
    LzoInputStream stream = new LzoInputStream(in, decompressor);
    OutputStream outputStream = new FileOutputStream(new File("C:\\Users\\victoryxs\\Desktop\\10.180.244.104_36310_20160218090000_S1_MME.csv"));
    int read = 0;
    byte[] bytes = new byte[1024];

    while ((read = stream.read(bytes)) != -1) {
      outputStream.write(bytes, 0, read);
    }
    outputStream.close();
    stream.close();
  }
}
```

the error is 
```
2016-02-29 15:53:28,279 (main) [INFO - org.anarres.lzo.LzoInputStream.logState(LzoInputStream.java:111)] 

2016-02-29 15:53:28,283 (main) [INFO - org.anarres.lzo.LzoInputStream.logState(LzoInputStream.java:112)] IndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: 0 Input buffer size=854554
2016-02-29 15:53:28,285 (main) [INFO - org.anarres.lzo.LzoInputStream.logState(LzoInputStream.java:113)] IndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: 0 Output buffer pos=0; length=0; size=0
Exception in thread "main" java.io.IOException: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.anarres.lzo.LzoInputStream.decompress(LzoInputStream.java:156)
	at org.anarres.lzo.LzoInputStream.readBlock(LzoInputStream.java:133)
	at org.anarres.lzo.LzoInputStream.fill(LzoInputStream.java:119)
	at org.anarres.lzo.LzoInputStream.read(LzoInputStream.java:102)
	at org.anarres.lzo.LzoInputStream.read(LzoInputStream.java:97)
	at testUnlzo.main(testUnlzo.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.anarres.lzo.LzoDecompressor1x.decompress(LzoDecompressor1x.java:7921)
	at org.anarres.lzo.LzoDecompressor1x.decompress(LzoDecompressor1x.java:8336)
	at org.anarres.lzo.LzoInputStream.decompress(LzoInputStream.java:142)
	... 10 more
```

**Comment by zman0900** [comment]
Any chance of fixing this, or adding some option to try ignore it?  I'm getting a similar error when trying to decompress a file created with Twitter's [hadoop-lzo](https://github.com/twitter/hadoop-lzo) 0.4.20.  

    java.io.IOException: Compressed with incompatible lzo version: 0x2060 (expected 0x2050)

I'm am using it like so:

```Java
org.apache.hadoop.fs.Path file = ...
try (InputStream stream = new LzopInputStream(file.getFileSystem(hadoopConf).open(file))) {
    // Do stuff with stream
}
```

EDIT:
I realized the problem here is that LZO is not forwards-compatible.  This library appears to have been originally created from the liblzo2 2.05 source, while Twitter's hadoop-lzo uses whatever liblzo2 is installed, which is 2.0.6 in my hadoop cluster.  

There is a check in this library's code to error out if the file to decompress has been compressed with a newer version.  If I use a debugger and force that check to pass, decompression works anyway, but I may have just gotten lucky with my specific file.  

Seems like this library will need to eventually be updated to match the changes in newer versions of liblzo2, which I assume will not be an easy task.
