### ISSUE TITLE
can't decompressor file

### ISSUE THREAD

**Issue by victoryxs** [shevek/lzo-java#8]
I write a simple demo to decompress lzo file

``` java
public class testUnlzo {

  public static void main(String[] args) throws Exception{
    InputStream in = new FileInputStream(new File("C:\\Users\\victoryxs\\Desktop\\10.180.244.104_36310_20160218090000_S1_MME.csv.lzo"));
    LzoAlgorithm algorithm = LzoAlgorithm.LZO1X;
    LzoDecompressor decompressor = LzoLibrary.getInstance().newDecompressor(algorithm, null);
    LzoInputStream stream = new LzoInputStream(in, decompressor);
    OutputStream outputStream = new FileOutputStream(new File("C:\\Users\\victoryxs\\Desktop\\10.180.244.104_36310_20160218090000_S1_MME.csv"));
    int read = 0;
    byte[] bytes = new byte[1024];

    while ((read = stream.read(bytes)) != -1) {
      outputStream.write(bytes, 0, read);
    }
    outputStream.close();
    stream.close();
  }
}
```

but the error is

```
2016-02-29 15:53:28,279 (main) [INFO - org.anarres.lzo.LzoInputStream.logState(LzoInputStream.java:111)] 

2016-02-29 15:53:28,283 (main) [INFO - org.anarres.lzo.LzoInputStream.logState(LzoInputStream.java:112)] IndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: 0 Input buffer size=854554
2016-02-29 15:53:28,285 (main) [INFO - org.anarres.lzo.LzoInputStream.logState(LzoInputStream.java:113)] IndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: 0 Output buffer pos=0; length=0; size=0
Exception in thread "main" java.io.IOException: java.lang.ArrayIndexOutOfBoundsException: 0
    at org.anarres.lzo.LzoInputStream.decompress(LzoInputStream.java:156)
    at org.anarres.lzo.LzoInputStream.readBlock(LzoInputStream.java:133)
    at org.anarres.lzo.LzoInputStream.fill(LzoInputStream.java:119)
    at org.anarres.lzo.LzoInputStream.read(LzoInputStream.java:102)
    at org.anarres.lzo.LzoInputStream.read(LzoInputStream.java:97)
    at testUnlzo.main(testUnlzo.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at org.anarres.lzo.LzoDecompressor1x.decompress(LzoDecompressor1x.java:7921)
    at org.anarres.lzo.LzoDecompressor1x.decompress(LzoDecompressor1x.java:8336)
    at org.anarres.lzo.LzoInputStream.decompress(LzoInputStream.java:142)
    ... 10 more

```

**Comment by dornan2** [comment]
Hello did you ever find a solution to this problem?

**Comment by victoryxs** [comment]
yes，use lzopinputstream to instead of lzoinputstream

**Comment by shevek** [comment]
Makes sense, lzop is a file format; lzo is a stream format. Thank you.
